// lib/pwa.ts — helpers for the Web Push permission flow (see hooks/usePushSubscription.ts)

// iOS Safari only delivers push to a site the user has added to their Home
// Screen — there is no way to request permission from a plain browser tab,
// so callers must branch on this before ever calling Notification.requestPermission().
export function isIOS(): boolean {
    if (typeof navigator === 'undefined') return false;
    const ua = navigator.userAgent;
    // iPadOS 13+ reports as "MacIntel" in the UA string but exposes multi-touch,
    // unlike a real Mac — this is the standard feature-detection workaround.
    const isIPadOS = navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1;
    return /iPad|iPhone|iPod/.test(ua) || isIPadOS;
}

export function isStandalone(): boolean {
    if (typeof window === 'undefined') return false;
    const nav = window.navigator as Navigator & { standalone?: boolean };
    return window.matchMedia('(display-mode: standalone)').matches || nav.standalone === true;
}

// Converts the VAPID public key (base64url, as generated by web-push) into the
// Uint8Array format PushManager.subscribe()'s applicationServerKey expects.
export function urlBase64ToUint8Array(base64String: string): Uint8Array {
    const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);
    for (let i = 0; i < rawData.length; i++) {
        outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
}
